"""
YADEM Explainability Report Generator
=============================================================================
Generates human-readable PDF/text reports from SHAP explanations.
"""

from typing import Dict, List
from datetime import datetime
from loguru import logger


class ReportGenerator:
    """Generates formatted credit decision reports."""

    def __init__(self):
        logger.info("Report Generator initialized")

    def generate_text_report(self, score_result: Dict, explanation: Dict,
                             applicant_info: Dict = None) -> str:
        """Generate a human-readable text report for a credit decision."""
        lines = []
        lines.append("=" * 70)
        lines.append("            YADEM CREDIT DECISION REPORT")
        lines.append("=" * 70)
        lines.append(f"  Report Date: {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}")
        lines.append(f"  Application ID: {score_result.get('application_id', 'N/A')}")
        lines.append("")

        # Applicant Summary
        if applicant_info:
            lines.append("  APPLICANT SUMMARY")
            lines.append("  " + "-" * 40)
            lines.append(f"  Business: {applicant_info.get('business_name', 'N/A')}")
            lines.append(f"  Sector: {applicant_info.get('business_sector', 'N/A')}")
            lines.append(f"  Years Operating: {applicant_info.get('years_in_business', 'N/A')}")
            lines.append(f"  Requested Amount: ₦{applicant_info.get('loan_amount_requested', 0):,.0f}")
            lines.append("")

        # Score Summary
        lines.append("  CREDIT DECISION")
        lines.append("  " + "-" * 40)
        score = score_result.get("yadem_score", 0)
        band = score_result.get("risk_band", "N/A")
        decision = score_result.get("decision", "N/A")
        lines.append(f"  YADEM Score: {score}/1,000")
        lines.append(f"  Risk Band: {band}")
        lines.append(f"  Decision: {decision}")
        lines.append("")

        # Score Visualization
        bar_len = 50
        filled = int((score / 1000) * bar_len)
        bar = "█" * filled + "░" * (bar_len - filled)
        lines.append(f"  Score: [{bar}] {score}")
        lines.append(f"         0                              1,000")
        lines.append("")

        # Top Factors
        top_factors = explanation.get("top_factors", [])
        if top_factors:
            lines.append("  KEY FACTORS IN YOUR DECISION")
            lines.append("  " + "-" * 40)
            for i, factor in enumerate(top_factors[:5], 1):
                direction = "↑" if factor.get("impact", 0) > 0 else "↓"
                lines.append(
                    f"  {i}. {direction} {factor.get('feature', 'Unknown')}: "
                    f"{factor.get('explanation', 'N/A')}"
                )
            lines.append("")

        # Recommendations (for declined/borderline)
        if decision in ("DECLINED", "MANUAL_REVIEW"):
            lines.append("  RECOMMENDATIONS FOR IMPROVEMENT")
            lines.append("  " + "-" * 40)
            recommendations = self._generate_recommendations(top_factors, score_result)
            for i, rec in enumerate(recommendations, 1):
                lines.append(f"  {i}. {rec}")
            lines.append("")

        # Disclaimer
        lines.append("  " + "-" * 40)
        lines.append("  This report is generated by the YADEM AI Credit Engine.")
        lines.append("  Decisions are based on data provided and statistical models.")
        lines.append("  You have the right to request a human review of this decision")
        lines.append("  under the Nigeria Data Protection Act 2023.")
        lines.append("=" * 70)

        return "\n".join(lines)

    def generate_lender_report(self, score_result: Dict, explanation: Dict) -> Dict:
        """Generate a structured report for lender dashboard."""
        return {
            "summary": {
                "score": score_result.get("yadem_score", 0),
                "band": score_result.get("risk_band", "E"),
                "decision": score_result.get("decision", "UNKNOWN"),
                "confidence": score_result.get("confidence", 0),
            },
            "risk_profile": {
                "default_probability": score_result.get("probability_of_default", 0),
                "model_agreement": score_result.get("model_agreement", 0),
            },
            "top_factors": explanation.get("top_factors", [])[:10],
            "fraud_check": score_result.get("fraud_check", {}),
            "rules_applied": score_result.get("rules_applied", []),
            "generated_at": datetime.utcnow().isoformat(),
        }

    def _generate_recommendations(self, top_factors: List[Dict],
                                   score_result: Dict) -> List[str]:
        """Generate actionable recommendations based on negative factors."""
        recommendations = []

        for factor in top_factors:
            feature = factor.get("feature", "").lower()
            impact = factor.get("impact", 0)

            if impact < 0:  # Negative impact features
                if "revenue" in feature or "cashflow" in feature:
                    recommendations.append(
                        "Increase and stabilize monthly revenue. "
                        "Consider diversifying income streams."
                    )
                elif "default" in feature or "delinquen" in feature:
                    recommendations.append(
                        "Clear any outstanding defaults before reapplying."
                    )
                elif "business_age" in feature or "years" in feature:
                    recommendations.append(
                        "Build longer business operating history. "
                        "Reapply after 12+ months of operations."
                    )
                elif "bureau" in feature or "credit" in feature:
                    recommendations.append(
                        "Improve credit bureau score by maintaining "
                        "timely repayments on existing obligations."
                    )

        if not recommendations:
            recommendations.append(
                "Contact a YADEM financial advisor for personalized guidance."
            )

        return recommendations[:5]
